### ISSUE TITLE
Branch tidy up

### ISSUE THREAD

**Issue by pelson** [conda-forge/numpy-feedstock#10]
Now that we have v1.10 on anaconda.org I'm going to make sure that the v1.10.x branch's commits are available from master, and then we can remove the branch. The only reason for wanting multiple branches in a feedstock is if we _know_ we will need to re-build from multiple version series. If it crops up unexpectedly that we need to rebuild v1.10, we can revive it from the commit and branch from there (as you would when developing normally). We don't need to keep v1.10_x around indefinitely.

**Comment by jakirkham** [comment]
Do we really need to force push and rebase this? I think we lose a lot of important history doing that and would **really** rather not.

**Comment by pelson** [comment]
Will hold fire until I'm back. But we don't need branches lying around which we never intend to update. We should use the same development principles as we do for software when it comes to branching.

**Comment by jakirkham** [comment]
Could we not just say we are not accepting PRs to a branch any more?

I understand that NumPy 1.10.x will be dropped and sooner rather than later (NumPy is trying to move to a 3 month minor release cycle). Still I think it is valuable to have this history. If someone (for whatever reason) needs to build 1.10.x, we have paved the path before them. Also, if old issues crop up, we can revisit this history to solve the problem.

Anyways, this seems like new territory for conda-forge. Should we add it to the hackpad and discuss?

**Comment by pelson** [comment]
> Still I think it is valuable to have this history

That's what commit are for, right? 😄 

> Should we add it to the hackpad and discuss?

Definitely. 👍

**Comment by jakirkham** [comment]
We have since consolidated the old branches by making no-op merges into `master`. So there is only one branch now.
