### ISSUE TITLE
Are microarch-level builds of interest, or even useful?

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/numpy-feedstock#342]
### Comment:

As I'm fairly certain the NumPy maintainers are aware of, [conda-forge supports microarch-level builds for x86 archs](https://conda-forge.org/docs/maintainer/knowledge_base/#microarch). As NumPy currently doesn't have this enabled I'm going to assume that is for a reason, but to double check and use this as a piece of information for the rest of the community, is that because NumPy already has optimizations that don't require SIMD optimizations to be turned on? Is adding the microarch-level builds going to be too many packages per build for limited utility, and the NumPy team doesn't want to use lots of storage? Are the additional builds enough of a nuisance that this level of maintainer overhead not worthwhile? Have the maintainers not had the opportunity to properly do comparisons on if the level-3 SIMD optimizations are worth it? Something else?

Again, this is asking out of curiosity and to better inform other project decisions, not to insinuate that the NumPy team should be doing something more than everything you already do.

**Comment by rgommers** [comment]
It's because NumPy has built-in dynamic dispatch, so users are already getting CPU-specific SIMD code paths right now. Dynamic dispatch is quite complex to implement, but a lot nicer on the packaging system than microarch builds.

Note that I am enthusiastic about microarch builds though - for SciPy and other packages where building for newer CPUs can give meaningful gains, and that don't have dynamic dispatch.

**Comment by matthewfeickert** [comment]
> It's because NumPy has built-in dynamic dispatch, so users are already getting CPU-specific SIMD code paths right now. Dynamic dispatch is quite complex to implement, but a lot nicer on the packaging system than microarch builds.

Awesome. This is what I assumed, but I wanted to be sure. Thanks for the quick response, @rgommers!

**Comment by matthewfeickert** [comment]
> Note that I am enthusiastic about microarch builds though - for SciPy and other packages where building for newer CPUs can give meaningful gains, and that don't have dynamic dispatch.

@rgommers one follow up question here: As https://github.com/conda-forge/scipy-feedstock doesn't have microarch builds supported, is this for any of the reasons in my original question?

**Comment by rgommers** [comment]
No, it's because no one has investigated the benefits of doing that yet. We have to see specific speedups to make it worthwhile. I think we should see them at least for `scipy.fft` (see https://github.com/scipy/scipy/issues/16984) and perhaps for other submodules, but it's not a given that it'll be worthwhile - see https://github.com/scientific-python/faster-scientific-python-ideas/issues/11#issuecomment-2494377023.
